export const START_FETCHING = 'START_FETCHING';
export const START_FETCHING_FILMS = 'START_FETCHING_FILMS';
export const RECEIVED_PAGES_DATA = 'RECEIVED_DATA';
export const RECEIVED_FILMS = 'RECEIVED_FILMS';
export const SHOW_PREV_HERO_IN_CURRENT_PAGE = 'SHOW_PREV_HERO_IN_CURRENT_PAGE';
export const SHOW_NEXT_HERO_IN_CURRENT_PAGE = 'SHOW_NEXT_HERO_IN_CURRENT_PAGE';
export const SHOW_PREV_HERO = 'SHOW_PREV_HERO';
export const SHOW_NEXT_HERO = 'SHOW_NEXT_HERO';
// Git hub ActionTypes
export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';
export const ON_FORM_SUBMIT = 'ON_FORM_SUBMIT';
export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const RECEIVED_USER_DATA = 'RECEIVED_USER_DATA';
export const RESET_USER_DATA = 'RESET_USER_DATA';
export const ERROR_USER_IS_THE_SAME = 'ERROR_USER_IS_THE_SAME';
export const ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
export const CANCEL_ERROR = 'CANCEL_ERROR';
