export const START_FETCHING = 'START_FETCHING';
export const START_FETCHING_FILMS = 'START_FETCHING_FILMS';
export const RECEIVED_PAGES_DATA = 'RECEIVED_DATA';
export const RECEIVED_FILMS = 'RECEIVED_FILMS';
export const SHOW_PREV_HERO_IN_CURRENT_PAGE = 'SHOW_PREV_HERO_IN_CURRENT_PAGE';
export const SHOW_NEXT_HERO_IN_CURRENT_PAGE = 'SHOW_NEXT_HERO_IN_CURRENT_PAGE';
